// runs on Keil MDK4, startup code generated by CubeMX 


while(1)
{
		if (GPIO_PIN_SET == HAL_GPIO_ReadPin(B1_GPIO_Port, B1_Pin)) {
		GPIOD->BSRR = LD4_Pin; /* another useful HAL function */
                HAL_Delay( 30);   //Stop for 30ms
		HAL_GPIO_TogglePin( GPIOD, LD4_Pin);
		 HAL_GPIO_TogglePin( GPIOD, LD3_Pin);
		 HAL_Delay( 30);
	 	 HAL_GPIO_TogglePin( GPIOD, LD3_Pin);
		 HAL_GPIO_TogglePin( GPIOD, LD5_Pin); /* another useful HAL function */
                 HAL_Delay( 30);   //Stop for 30ms
		 HAL_GPIO_TogglePin( GPIOD, LD5_Pin);
		 HAL_GPIO_TogglePin( GPIOD, LD6_Pin);
		 HAL_Delay( 30);
		 HAL_GPIO_TogglePin( GPIOD, LD6_Pin);
			
		}
